minio:
  endpoint: http://172.20.10.5:9004
  accessKey: admin
  secretKey: 12345678
  bucketName: test

spring:
  # ??????????
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 3001